### ISSUE TITLE
How to generate slot.pt?

### ISSUE THREAD

**Issue by kongds** [wzh9969/contrastive-htc#1]
Thank you for providing code.
Thanks for providing the code, but I encountered the following error when training

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/19282154/158508291-9f4280da-4d14-461d-8058-1f80c5c2ad57.png">

**Comment by wzh9969** [comment]
That line of code was deleted accidentally. Now we add it back. A rerun of `data_wos.py` should fix the problem.

**Comment by kongds** [comment]
Thank you

**Comment by kongds** [comment]
Hello, I follow the below commands to reproduce HGCLR in WOS.
`
python train.py --name test --batch 12 --data WebOfScience --lambda 0.1 --thre 0.02
`

But i only get `macro 0.8106568462953676 micro 0.8673255626577859` for checkpoint_best_macro.pt and `macro 0.8035417498124795 micro 0.8643072613660849` for checkpoint_best_micro.pt.

Did I forget some steps?

**Comment by wzh9969** [comment]
This is quite normal since something like a different GPU or running environment may affect the result. But I will double-check the code to make sure all parameters are set correctly.

**Comment by mmx1997** [comment]
amazing
