### ISSUE TITLE
请问原始样本和正样本的bert是否参数完全一致？

### ISSUE THREAD

**Issue by amal-spec** [wzh9969/contrastive-htc#10]
如题。如果参数完全一致的话，将层次结构注入到bert编码器的过程，通过对比学习会微调反向传播更新bert参数？那么更新的是哪个bert呢？正样本和原始样本bert编码的顺序是否对结果有影响？

**Comment by wzh9969** [comment]
公用一个BERT，两个样本的梯度会相加之后更新。这里对比学习的本质思想是原样本表示与带有结构信息的表示尽量接近，那么可以认为原样本表示中就携带了结构信息。

**Comment by amal-spec** [comment]
谢谢。也就是说正样本和原始样本bert编码的顺序不会对结果有影响。最后的损失函数由对比学习损失和分类损失组成，本质上都是为了反向传播更新bert参数？之后在测试阶段应用训练好的bert进行分类？可以这么理解吗？

**Comment by wzh9969** [comment]
是的

**Comment by amal-spec** [comment]
楼主那我有个疑惑，既然对比学习损失和分类损失本质上都是为了反向传播更新bert参数，那对于论文中的这部分应该怎么理解呢？We assume the positive sample should retain the labels, so we use classification loss of the positive sample as a guidance of the graph encoder and the positive sample generation.

**Comment by wzh9969** [comment]
在假设正样本标签不改变的情况下，正样本的分类损失不仅受到BERT的影响，也受到正样本质量的影响。所以正样本的分类损失同时也会更新正样本生成相关的参数，希望可以生成高质量的正样本。
