### ISSUE TITLE
请问对比学习模块为什么要添加一个relu层呢？

### ISSUE THREAD

**Issue by amal-spec** [wzh9969/contrastive-htc#12]
如题。是用bert的CLS输出作为文本表示后，为何在对比学习模块又添加了一个非线性层RELU呢？这个的作用是什么呢？直接使用bert的CLS输出作为文本表示进行对比损失会产生什么影响呢？

**Comment by wzh9969** [comment]
请参考其他对比学习文章：[ICML2020](http://proceedings.mlr.press/v119/chen20j.html)
