### ISSUE TITLE
请问温度系数越大效果更好是为什么呢？有什么理论支撑吗

### ISSUE THREAD

**Issue by amal-spec** [wzh9969/contrastive-htc#13]
如题。We also find that a higher tau (e.g. tau=2) is beneficial but we keep it to  for simplicity.请问是什么原因呢？温度系数越大不是越将所有负样本视为一致了吗，为何效果更佳呢?

**Comment by wzh9969** [comment]
这是调参的发现，没有理论支撑，因此并没有在文章中提及。
