### ISSUE TITLE
two wired numbers in graph model

### ISSUE THREAD

**Issue by ddz5431** [wzh9969/contrastive-htc#17]
edge_mat = torch.zeros(len(inverse_label_list), len(inverse_label_list), 15, dtype=torch.long)
self.distance_embedding = nn.Embedding(20, 1, 0)

Question: why do you set 15 as the third dimension size of edge matrix and 20 as the first dimension size of distance embedding? Do they differ from other numbers?

**Comment by wzh9969** [comment]
They are set casually. These two numbers can be set to any number larger than the maximum distance between two nodes. I set to 15 and 20 because they work just fine and there is no need to tune these numbers according to different datasets.

**Comment by ddz5431** [comment]
ok thanks!
