### ISSUE TITLE
loss下降，评价指标为0

### ISSUE THREAD

**Issue by zpp13** [wzh9969/contrastive-htc#2]
如题，docker内安装依赖环境，WOS数据集
python train.py --name test --batch 12 --data WebOfScience --lamb 0.1 --thre 0.02
随着训练过程，loss从1.8逐渐下降到0.8，但是macro和micro一直徘徊在0周围，请问大佬遇到过这种情况吗？

**Comment by wzh9969** [comment]
对比学习对batch size比较敏感，可以适当调小lambda和gamma

**Comment by zpp13** [comment]
多谢回复，我试试。但是我用的就是您推荐的参数，请问您实际做实验的参数是怎样的呢？

**Comment by wzh9969** [comment]
我们实验的参数就是当前推荐的参数，但是我们发现Transformers版本会有影响。我们发现lambda=0.05会稳定一些，但是结果稍低，主表里的结果是在Transformers==4.2.1, lambda=0.05下得到的。推荐的0.1可以在不固定种子时跑到更好的结果，但是因为不可复现所以没有汇报。

**Comment by zpp13** [comment]
data/WebOfScience/Meta-data/Data.txt如下：
![1650013666(1)](https://user-images.githubusercontent.com/33889654/163551568-2d9570c9-8bde-4011-a969-6b3c9b0bdd03.jpg)
docker内pip安装过程如下：
![1650013751(1)](https://user-images.githubusercontent.com/33889654/163551582-8a79939e-53d2-409b-a157-5448627acfe7.png)
训练过程如下：
![1650013860(1)](https://user-images.githubusercontent.com/33889654/163551785-a6969c94-af59-4cb7-9f24-fb037b40ecbf.png)
评价指标打印的是训练过程中batch内的数据结果
代码内容我并没有修改，还请大佬指教，多谢。

**Comment by wzh9969** [comment]
我们没有遇到这种情况，这行代码在我们这里可以跑到主表中汇报的结果。我们的GPU是3090，下面是我们的第一个epoch。
<img width="1145" alt="2022-04-16 122852" src="https://user-images.githubusercontent.com/37007622/163661382-d2def40a-25bb-4520-a680-7f9597d7a2d1.png">
