### ISSUE TITLE
how to train on WOS-5736

### ISSUE THREAD

**Issue by ayushxx7** [wzh9969/contrastive-htc#20]
looks like the code trains on the whole excel (WOS-49685), is there a utility or standard way I should approach this? I am thinking of creating some sort of logic to filter out entries from Excel by using a mapping from WOS-5736 provided in the dataset. Although it doesn't list indexes, it has data points split into multiple files.

**Comment by wzh9969** [comment]
Please read the [Preprocess](https://github.com/wzh9969/contrastive-htc#preprocess) part in README.
