### ISSUE TITLE
The question about label information passed to GraphEncoder

### ISSUE THREAD

**Issue by crescentluna** [wzh9969/contrastive-htc#22]
On line 369 of the file graph.py, why is the label tensor used to multiply the output of the graph after applying the gumbel_softmax function? This may potentially leak label information to the contrast_mask tensor, which could aid in downstream classification tasks?

**Comment by wzh9969** [comment]
The leak is designed on purpose. The true label information is used to build high-quality positive samples for contrastive learning. After training, positive samples as well as true labels are not needed. 
Please refer to [our paper](https://aclanthology.org/2022.acl-long.491/) for detail explanation.
