### ISSUE TITLE
datas

### ISSUE THREAD

**Issue by zwweilai** [wzh9969/contrastive-htc#24]
hello，could you please give me the datasets of NTY and RCV-1？I can't get the datasets from the website. I promise that I will only use these datasets for researching.

**Comment by wzh9969** [comment]
Sorry I cannot give you due to the agreement I assigned. The link in `README.md` is still valid and you can download them by signing the agreements.

**Comment by zwweilai** [comment]
thank you for your help，so can you give me the real agreement and the website, the website that you given is the page of introduction, so could you help me? thank you very much



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Wang ***@***.***> |
| Date | 05/25/2023 16:29 |
| To | ***@***.***> |
| Cc | Zhanwang ***@***.***>***@***.***> |
| Subject | Re: [wzh9969/contrastive-htc] datas (Issue #24) |

Sorry I cannot give you due to the agreement I assigned. The link in README.md is still valid and you can download them by signing the agreements.

**Comment by wzh9969** [comment]
Links in readme are what you need. You can see agreements for RCV1 and the download link for NYT at the bottom. Please read those pages carefully.

**Comment by zwweilai** [comment]
thank you for your help



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Wang ***@***.***> |
| Date | 05/25/2023 17:55 |
| To | ***@***.***> |
| Cc | Zhanwang ***@***.***>***@***.***> |
| Subject | Re: [wzh9969/contrastive-htc] datas (Issue #24) |

Links in readme are what you need. You can see agreements for RCV1 and the download link for NYT at the bottom. Please read those pages carefully.

**Comment by L199Q** [comment]
Hello, have you obtained the dataset yet? We can explore together（ liuqiang21@nimte.ac.cn ）

**Comment by Ray-Lei-93** [comment]
I am unable to locate the download link as well. Is it the "Web Download" at the bottom of the page? Could you kindly provide me with the specific steps to successfully obtain the NYT dataset?
