### ISSUE TITLE
python depedencies

### ISSUE THREAD

**Issue by RomanPlaud** [wzh9969/contrastive-htc#26]
Hey, i would like to reproduce your results, could you provide a proper requirements.txt ? It's been a a day i've tried to setup a correct conda environment but i always have conflicts.

**Comment by wzh9969** [comment]
The proper package versions are listed in readme. Please follow those instructions carefully, especially with `torch-geometric == 1.7.2; torch-scatter == 2.0.8; torch-sparse == 0.6.12`. I have torch version == 1.6.0 & 1.8.0 and both work fine.
