### ISSUE TITLE
为什么我安装指定版本的transformers的tokenizers就是卡住安装不下去呀

### ISSUE THREAD

**Issue by pen-ho** [wzh9969/contrastive-htc#29]
pip install transformers==4.2.1 -i https://pypi.tuna.tsinghua.edu.cn/simple

执行这个时候一直卡在tokenizers的安装上，安装最新版本的transformers又跑不起来。BaseModelOutputWithPoolingAndCrossAttentions这个类报错。

**Comment by wzh9969** [comment]
请自行解决环境问题，尝试在全新的conda环境中配置。
