### ISSUE TITLE
关于运行data_wos.py报错的问题

### ISSUE THREAD

**Issue by supersomnr** [wzh9969/contrastive-htc#33]
作者您好，我按照requirement.txt文件配置好了环境，但是运行data_wos.py时，出现了一个错误（如下图）。百度之后还是不知道该怎么解决，请问您知道解决办法吗？
![image](https://github.com/wzh9969/contrastive-htc/assets/34056193/a3d17239-d990-4460-b582-421db65e4dfb)

**Comment by wzh9969** [comment]
您好，fairseq在某个版本后改变了这个类的使用方式，请适当降低fairseq的版本。我已对readme进行了更新，感谢您的反馈。

**Comment by supersomnr** [comment]
作者你好，上面问题已解决。但是训练的时候又报错了（如下图），我目前的cuda版本是12.4，我看您训练的cuda版本是11.2，请问是否需要将cuda降级到指定版本呢？
![1715680087952](https://github.com/wzh9969/contrastive-htc/assets/34056193/0ac762c6-2a75-49b6-93f2-718dcec699f3)

**Comment by wzh9969** [comment]
这个似乎是torch-geometric库的问题，请尝试严格按照reademe中的版本进行安装，或者使用[该库文档](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html)推荐的方式安装最新版本。如果没有性能要求，可以直接用`pip install torch_geometric`单独安装，不要安装torch-scatter和torch-sparse。

**Comment by supersomnr** [comment]
感谢您的回复！昨天重新安装了torch-geometric，问题已经解决🙏。



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2024年5月16日(周四) 下午5:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wzh9969/contrastive-htc] 关于运行data_wos.py报错的问题 (Issue #33)




 
这个似乎是torch-geometric库的问题，请尝试严格按照reademe中的版本进行安装，或者使用该库文档推荐的方式安装最新版本。如果没有性能要求，可以直接用pip install torch_geometric单独安装，不要安装torch-scatter和torch-sparse。
