### ISSUE TITLE
rcv1复现结果相差较大

### ISSUE THREAD

**Issue by amal-spec** [wzh9969/contrastive-htc#4]
大佬好，请问您的参数设置是否和论文一样？我在复现rcv1数据集的结果时，相差了1.5点，请问是否有参数设置不一样的地方？

**Comment by wzh9969** [comment]
文章中的参数在不固定种子的情况下可以得到更好的结果，为了复现性考虑主表格中的结果是固定了种子的，因此设置稍有区别，我已经更新在README中。另外我们发现不同的GPU以及transformers的版本都会影响结果。

**Comment by amal-spec** [comment]
您好，我看论文中写的rcv1 lamb值是0.1 您更新的readme里面写的是0.3，请问是哪个有误呀



---- 回复的原邮件 ----
| 发件人 | Wang ***@***.***> |
| 日期 | 2022年06月20日 13:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wzh9969/contrastive-htc] rcv1复现结果相差较大 (Issue #4) |

文章中的参数在不固定种子的情况下可以得到更好的结果，为了复现性考虑主表格中的结果是固定了种子的，因此设置稍有区别，我已经更新在README中。另外我们发现不同的GPU以及transformers的版本都会影响结果。
