### ISSUE TITLE
训练时长

### ISSUE THREAD

**Issue by YuboHe** [wzh9969/contrastive-htc#5]
您好，感觉网络结构还蛮复杂的，不知道WOS数据集，训练到论文中的表现需要多少个epoch呀，目前我用V100, 33min一轮，感觉时间好长

**Comment by wzh9969** [comment]
log里显示一共20个epoch，我们使用单卡3090单个epoch的训练时间是20min左右

**Comment by YuboHe** [comment]
谢谢回复
