### ISSUE TITLE
How long does training take on WOS?

### ISSUE THREAD

**Issue by RushiBhatt007** [wzh9969/contrastive-htc#6]
I see in the repo that GeForce RTX 3090 (24G) are used, but how much time did it take for training (WOS dataset)?

**Comment by wzh9969** [comment]
Our log shows that the model had trained 20 epochs on WOS and roughly 20 min/epoch.

**Comment by RushiBhatt007** [comment]
Oh, okay got it thank you very much. Are the results published for WOS only after 20 epochs? I'm a bit confused because the codebase had num of epochs set to 1000.

**Comment by wzh9969** [comment]
The early stop strategy controls the training process. The main loop will stop if performance on dev set does not increase for a certain epochs (lines 138-140 in `train.py`). We set num of epochs to 1000 to make sure it cannot stop too early but it will NEVER reach that number.
