### ISSUE TITLE
请问对于WOS数据集来说，怎么获得模型推断得到的标签呢？

### ISSUE THREAD

**Issue by wuyaoxuehun** [wzh9969/contrastive-htc#9]
如题，是不是直接在第二级标签上argmax logits呢，还是先在第一级再在第二级做argmax呢？
谢谢！

**Comment by wzh9969** [comment]
这个问题本质是一个多标签的分类，不知道输入对应的标签个数。所以目前的解决方法是对每个标签进行0-1的二分类，代码实现里判断logits是否大于0。WOS数据集比较特殊，两层标签且固定每层一个，为了和其他数据集保持一致没有进行特殊处理。
